# Deepdevflow Main Configuration

app:
  name: "Deepdevflow"
  version: "0.1.0"
  debug: true

server:
  host: "127.0.0.1"
  port: 8000
  workers: 4
  reload: true
  cors:
    allow_origins: ["*"]
    allow_credentials: true
    allow_methods: ["*"]
    allow_headers: ["*"]

database:
  connection_string: "sqlite:///data/deepdevflow.db"
  echo: false
  pool_size: 5
  max_overflow: 10
  pool_recycle: 3600

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/deepdevflow.log"
  max_size: 10485760  # 10MB
  backup_count: 5

agent:
  default_agent: "HostAgent"
  max_tasks_per_agent: 10
  task_timeout: 300  # seconds
  allow_remote_agents: true

llm:
  default_provider: "openai"
  timeout: 60  # seconds
  retries: 3
  retry_delay: 1  # seconds

security:
  api_key_header: "X-API-Key"
  token_expire_minutes: 1440  # 24 hours
  secret_key: "CHANGE_THIS_TO_A_SECURE_RANDOM_STRING"
